---
- name: Installing common packages 
  include: "packages-common.yml"
  become: true

- name: Installing mariadb server
  include: "packages-server.yml"
  become: true

- name: Setting up repositories
  include: "databases.yml"
  become: true
