- name: Install server packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python-mysqldb
  tags:
    - apt
    - db
    - mariadb
    - mariadb-server
    - packages
