- name: Install client packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - mariadb-client
  when: mariadb_install_client
  tags:
    - apt
    - db
    - mariadb
    - mariadb-client
    - packages

