---
- name: Configure mariadb to listen on all interfaces
  lineinfile:
    regexp: "^bind-address"
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    line: "bind-address = {{ mariadb_bind_address }}"
  tags:
    - db
    - mariadb

- name: Deploy MariaDB profile
  template:
    src: mariadb-server.j2
    dest: /etc/ufw/applications.d/mariadb-server
  tags:
    - db
    - mariadb

- name: Ufw
  ufw:
    name: MariaDB
    rule: allow
    delete: "{% if ufw_mariadb_public %}no{% else %}yes{% endif %}"
  tags:
    - db
    - mariadb
    - ufw
